server.name: kibana
server.host: 0.0.0.0
server.port: 5601
server.basePath: /kibana
server.rewriteBasePath: false

elasticsearch.hosts: [ "http://elasticsearch:9200" ]

monitoring.ui.container.elasticsearch.enabled: true
